import { EstadoAsignatura } from '../../../domain/value-objects/course-status.vo';

export interface CarreraSeed {
  codigo: string;
  nombre: string;
  asignaturas: AsignaturaSeed[];        // Solo malla
  modulosIngles?: AsignaturaSeed[];     // Inglés de coordinación de idiomas
  practicas?: AsignaturaSeed[];         // Prácticas
}

export interface AsignaturaSeed {
  codigo: string;
  nombre: string;
  sct: number;
  nivel: number;
  requisitos?: string[];
}

const REQUISITOS_II_HASTA_NIVEL_4 = [
  'II-001',
  'II-002',
  'II-003',
  'II-004',
  'II-005',
  'II-006',
  'II-007',
  'II-008',
  'II-009',
  'II-010',
  'II-011',
  'II-012',
  'II-013',
  'II-014',
  'II-015',
  'II-016',
  'II-017',
  'II-018',
  'II-019',
];

const REQUISITOS_II_HASTA_NIVEL_7 = [
  ...REQUISITOS_II_HASTA_NIVEL_4,
  'II-020',
  'II-021',
  'II-022',
  'II-023',
  'II-024',
  'II-025',
  'II-026',
  'II-027',
  'II-028',
  'II-029',
  'II-030',
  'II-031',
  'II-032',
  'II-033',
  'II-034',
  'II-035',
];

const REQUISITOS_II_HASTA_NIVEL_9 = [
  ...REQUISITOS_II_HASTA_NIVEL_7,
  'II-036',
  'II-037',
  'II-038',
  'II-039',
  'II-040',
  'II-041',
  'II-042',
  'II-043',
  'II-044',
];

export const CARRERAS_SEED: CarreraSeed[] = [
  {
    codigo: 'icc',
    nombre: 'Ingenieria Civil Informatica',
    asignaturas: [
      { codigo: 'ICC-001', nombre: 'Ingenieria y Sociedad', sct: 4, nivel: 1 },
      { codigo: 'ICC-002', nombre: 'Fundamentos de Calculo', sct: 6, nivel: 1 },
      { codigo: 'ICC-003', nombre: 'Algebra', sct: 6, nivel: 1 },
      {
        codigo: 'ICC-004',
        nombre: 'Introduccion a la Quimica',
        sct: 5,
        nivel: 1,
      },
      {
        codigo: 'ICC-005',
        nombre: 'Habilidades Comunicativas en Ingenieria',
        sct: 3,
        nivel: 1,
      },
      {
        codigo: 'ICC-006',
        nombre: 'Introduccion al Diseno de Ingenieria',
        sct: 5,
        nivel: 2,
      },
      {
        codigo: 'ICC-007',
        nombre: 'Calculo en una variable',
        sct: 6,
        nivel: 2,
        requisitos: ['ICC-002'],
      },
      {
        codigo: 'ICC-008',
        nombre: 'Matematica para la Computacion',
        sct: 4,
        nivel: 2,
      },
      {
        codigo: 'ICC-009',
        nombre: 'Fisica I',
        sct: 6,
        nivel: 2,
        requisitos: ['ICC-002'],
      },
      {
        codigo: 'ICC-010',
        nombre: 'Laboratorio de Ciencias',
        sct: 5,
        nivel: 2,
      },
      {
        codigo: 'ICC-011',
        nombre: 'Fundamentos de Ecodiseno',
        sct: 4,
        nivel: 3,
      },
      {
        codigo: 'ICC-012',
        nombre: 'Calculo Multivariable',
        sct: 5,
        nivel: 3,
        requisitos: ['ICC-007'],
      },
      {
        codigo: 'ICC-013',
        nombre: 'Algebra Lineal',
        sct: 5,
        nivel: 3,
        requisitos: ['ICC-003'],
      },
      {
        codigo: 'ICC-014',
        nombre: 'Fisica II',
        sct: 6,
        nivel: 3,
        requisitos: ['ICC-007', 'ICC-009'],
      },
      { codigo: 'ICC-015', nombre: 'Electivo de Ingenieria', sct: 3, nivel: 3 },
      {
        codigo: 'ICC-016',
        nombre: 'Taller de Programacion',
        sct: 3,
        nivel: 3,
        requisitos: ['ICC-010'],
      },
      {
        codigo: 'ICC-017',
        nombre: 'Taller de Diseno de Ingenieria',
        sct: 6,
        nivel: 4,
        requisitos: ['ICC-006', 'ICC-011'],
      },
      {
        codigo: 'ICC-018',
        nombre: 'Programacion Orientada a Objetos',
        sct: 5,
        nivel: 4,
        requisitos: ['ICC-016'],
      },
      {
        codigo: 'ICC-019',
        nombre: 'Ecuaciones Diferenciales',
        sct: 6,
        nivel: 4,
        requisitos: ['ICC-013'],
      },
      {
        codigo: 'ICC-020',
        nombre: 'Fisica III',
        sct: 5,
        nivel: 4,
        requisitos: ['ICC-012', 'ICC-014'],
      },
      {
        codigo: 'ICC-021',
        nombre: 'Taller de computacion',
        sct: 4,
        nivel: 4,
        requisitos: ['ICC-015'],
      },
      {
        codigo: 'ICC-022',
        nombre: 'Electivo Formacion General I',
        sct: 3,
        nivel: 4,
      },
      {
        codigo: 'ICC-023',
        nombre: 'Economia y Finanzas Empresariales',
        sct: 5,
        nivel: 5,
        requisitos: ['ICC-006'],
      },
      {
        codigo: 'ICC-024',
        nombre: 'Probabilidad y Estadistica para Ingenieria',
        sct: 5,
        nivel: 5,
        requisitos: ['ICC-012'],
      },
      {
        codigo: 'ICC-025',
        nombre: 'Bases de Datos',
        sct: 4,
        nivel: 5,
        requisitos: ['ICC-018'],
      },
      {
        codigo: 'ICC-026',
        nombre: 'Internet y Sistemas Operativos',
        sct: 6,
        nivel: 5,
        requisitos: ['ICC-021'],
      },
      {
        codigo: 'ICC-027',
        nombre: 'Algoritmos y Paradigmas',
        sct: 6,
        nivel: 5,
        requisitos: ['ICC-018'],
      },
      {
        codigo: 'ICC-028',
        nombre: 'Electivo Formacion General II',
        sct: 3,
        nivel: 5,
      },
      {
        codigo: 'ICC-029',
        nombre: 'Formulacion y Evaluacion de Proyectos',
        sct: 4,
        nivel: 6,
      },
      {
        codigo: 'ICC-030',
        nombre: 'Ciencias de la Computacion',
        sct: 5,
        nivel: 6,
        requisitos: ['ICC-013'],
      },
      {
        codigo: 'ICC-031',
        nombre: 'Taller de Bases de Datos',
        sct: 6,
        nivel: 6,
        requisitos: ['ICC-025'],
      },
      {
        codigo: 'ICC-032',
        nombre: 'Computacion en la Nube',
        sct: 6,
        nivel: 6,
        requisitos: ['ICC-026'],
      },
      {
        codigo: 'ICC-033',
        nombre: 'Ingenieria de Software',
        sct: 6,
        nivel: 6,
        requisitos: ['ICC-027'],
      },
      {
        codigo: 'ICC-034',
        nombre: 'Diseno de Negocios Innovadores',
        sct: 4,
        nivel: 7,
        requisitos: ['ICC-023'],
      },
      {
        codigo: 'ICC-035',
        nombre: 'Sistemas Inteligentes',
        sct: 6,
        nivel: 7,
        requisitos: ['ICC-030'],
      },
      {
        codigo: 'ICC-036',
        nombre: 'Ingenieria de Datos',
        sct: 4,
        nivel: 7,
        requisitos: ['ICC-025'],
      },
      {
        codigo: 'ICC-037',
        nombre: 'Ciberseguridad',
        sct: 6,
        nivel: 7,
        requisitos: ['ICC-026'],
      },
      {
        codigo: 'ICC-038',
        nombre: 'Diseno de Experiencia de Usuario',
        sct: 6,
        nivel: 7,
        requisitos: ['ICC-033'],
      },
      {
        codigo: 'ICC-039',
        nombre: 'Electivo Formacion General III',
        sct: 3,
        nivel: 7,
      },
      {
        codigo: 'ICC-040',
        nombre: 'Taller de Empresas Tecnologicas',
        sct: 5,
        nivel: 8,
        requisitos: ['ICC-034'],
      },
      {
        codigo: 'ICC-041',
        nombre: 'Taller de Ingenieria de Datos',
        sct: 7,
        nivel: 8,
        requisitos: ['ICC-036'],
      },
      {
        codigo: 'ICC-042',
        nombre: 'Taller de IoT y Robotica',
        sct: 5,
        nivel: 8,
        requisitos: ['ICC-035'],
      },
      {
        codigo: 'ICC-043',
        nombre: 'Taller de Ingenieria de Software',
        sct: 6,
        nivel: 8,
        requisitos: ['ICC-033'],
      },
      {
        codigo: 'ICC-044',
        nombre: 'Taller Habilidades Profesionales',
        sct: 4,
        nivel: 8,
        requisitos: ['ICC-039'],
      },
      {
        codigo: 'ICC-045',
        nombre: 'Diseno proyecto de Ingenieria Informatica',
        sct: 5,
        nivel: 9,
        requisitos: ['ICC-029', 'ICC-038'],
      },
      {
        codigo: 'ICC-046',
        nombre: 'Electivo de Especialidad I',
        sct: 4,
        nivel: 9,
        requisitos: ['ICC-035'],
      },
      {
        codigo: 'ICC-047',
        nombre: 'Electivo de Especialidad II',
        sct: 4,
        nivel: 9,
        requisitos: ['ICC-036'],
      },
      {
        codigo: 'ICC-048',
        nombre: 'Direccion de Proyectos',
        sct: 6,
        nivel: 9,
        requisitos: ['ICC-040'],
      },
      {
        codigo: 'ICC-049',
        nombre: 'Proyecto de Desarrollo de Software',
        sct: 7,
        nivel: 9,
        requisitos: ['ICC-043'],
      },
      {
        codigo: 'ICC-050',
        nombre: 'Electivo Formacion General IV',
        sct: 3,
        nivel: 9,
      },
      {
        codigo: 'ICC-051',
        nombre: 'Capstone Multidisciplinario',
        sct: 5,
        nivel: 10,
        requisitos: ['ICC-040'],
      },
      {
        codigo: 'ICC-052',
        nombre: 'Electivo de Especialidad III',
        sct: 4,
        nivel: 10,
        requisitos: ['ICC-046'],
      },
      {
        codigo: 'ICC-053',
        nombre: 'Investigacion Aplicada en Informatica',
        sct: 7,
        nivel: 10,
        requisitos: ['ICC-041'],
      },
      {
        codigo: 'ICC-054',
        nombre: 'Proyecto de Integracion de Informatica',
        sct: 6,
        nivel: 10,
        requisitos: ['ICC-048', 'ICC-045'],
      },
      {
        codigo: 'ICC-055',
        nombre: 'Electivo de Especialidad IV',
        sct: 4,
        nivel: 10,
        requisitos: ['ICC-043'],
      },
      {
        codigo: 'ICC-056',
        nombre: 'Actividad de Titulacion',
        sct: 29,
        nivel: 11,
        requisitos: ['ICC-051', 'ICC-052', 'ICC-053', 'ICC-054', 'ICC-055'],
      },
    ],
    modulosIngles: [
      { codigo: 'ICC-ING-1', nombre: 'Nivel Principiante', sct: 0, nivel: 1 },
      { codigo: 'ICC-ING-2', nombre: 'Nivel Basico', sct: 0, nivel: 2, requisitos: ['ICC-ING-1'] },
      { codigo: 'ICC-ING-3', nombre: 'Nivel Pre Intermedio', sct: 0, nivel: 3, requisitos: ['ICC-ING-2'] },
      { codigo: 'ICC-ING-4', nombre: 'Nivel Intermedio', sct: 0, nivel: 4, requisitos: ['ICC-ING-3'] },
    ],
    practicas: [
      {
        codigo: 'ICC-PRAC-1',
        nombre: 'Practica I',
        sct: 5,
        nivel: 1,
        requisitos: ['ICC-001', 'ICC-002', 'ICC-003', 'ICC-004', 'ICC-005',
                     'ICC-006', 'ICC-007', 'ICC-008', 'ICC-009', 'ICC-010',
                     'ICC-011', 'ICC-012', 'ICC-013', 'ICC-014', 'ICC-015', 'ICC-016',
                     'ICC-017', 'ICC-018', 'ICC-019', 'ICC-020', 'ICC-021', 'ICC-022',
                     'ICC-023', 'ICC-024', 'ICC-025', 'ICC-026', 'ICC-027', 'ICC-028']
      },
      {
        codigo: 'ICC-PRAC-2',
        nombre: 'Practica II',
        sct: 5,
        nivel: 2,
        requisitos: ['ICC-001', 'ICC-002', 'ICC-003', 'ICC-004', 'ICC-005',
                     'ICC-006', 'ICC-007', 'ICC-008', 'ICC-009', 'ICC-010',
                     'ICC-011', 'ICC-012', 'ICC-013', 'ICC-014', 'ICC-015', 'ICC-016',
                     'ICC-017', 'ICC-018', 'ICC-019', 'ICC-020', 'ICC-021', 'ICC-022',
                     'ICC-023', 'ICC-024', 'ICC-025', 'ICC-026', 'ICC-027', 'ICC-028',
                     'ICC-029', 'ICC-030', 'ICC-031', 'ICC-032', 'ICC-033', 'ICC-034',
                     'ICC-035', 'ICC-036', 'ICC-037', 'ICC-038', 'ICC-039', 'ICC-040',
                     'ICC-041', 'ICC-042', 'ICC-043', 'ICC-044', 'ICC-045', 'ICC-046', 'ICC-047']
      },
    ],
  },
  {
    codigo: 'ii',
    nombre: 'Ingenieria Informatica',
    asignaturas: [
      {
        codigo: 'II-001',
        nombre: 'Introduccion a Matematica',
        sct: 6,
        nivel: 1,
      },
      { codigo: 'II-002', nombre: 'Introduccion a Fisica', sct: 5, nivel: 1 },
      {
        codigo: 'II-003',
        nombre: 'Introduccion a la Programacion',
        sct: 7,
        nivel: 1,
      },
      {
        codigo: 'II-004',
        nombre: 'Desarrollo de Habilidades Comunicacionales',
        sct: 5,
        nivel: 1,
      },
      {
        codigo: 'II-005',
        nombre: 'Desarrollo de Habilidades de Pensamiento',
        sct: 5,
        nivel: 1,
      },
      {
        codigo: 'II-006',
        nombre: 'Matematica para Informatica I',
        sct: 6,
        nivel: 2,
        requisitos: ['II-001'],
      },
      {
        codigo: 'II-007',
        nombre: 'Fisica para Informatica I',
        sct: 5,
        nivel: 2,
        requisitos: ['II-002'],
      },
      {
        codigo: 'II-008',
        nombre: 'Programacion Orientada a Objetos',
        sct: 7,
        nivel: 2,
        requisitos: ['II-003'],
      },
      { codigo: 'II-009', nombre: 'Acceso a Datos', sct: 6, nivel: 2 },
      {
        codigo: 'II-010',
        nombre: 'Electivo de Formacion General I',
        sct: 3,
        nivel: 2,
      },
      {
        codigo: 'II-011',
        nombre: 'Matematica para Informatica II',
        sct: 7,
        nivel: 3,
        requisitos: ['II-006'],
      },
      { codigo: 'II-012', nombre: 'Estadistica Aplicada', sct: 7, nivel: 3 },
      {
        codigo: 'II-013',
        nombre: 'Lenguajes de Programacion',
        sct: 7,
        nivel: 3,
        requisitos: ['II-008'],
      },
      {
        codigo: 'II-014',
        nombre: 'Electivo de Formacion General II',
        sct: 3,
        nivel: 3,
      },
      {
        codigo: 'II-015',
        nombre: 'Proyecto de Aplicacion',
        sct: 6,
        nivel: 4,
        requisitos: ['II-013'],
      },
      {
        codigo: 'II-016',
        nombre: 'Hardware y Sistemas Operativos',
        sct: 6,
        nivel: 4,
      },
      {
        codigo: 'II-017',
        nombre: 'Programacion Avanzada',
        sct: 7,
        nivel: 4,
        requisitos: ['II-008'],
      },
      {
        codigo: 'II-018',
        nombre: 'Diseno de Bases de Datos',
        sct: 6,
        nivel: 4,
        requisitos: ['II-009'],
      },
      {
        codigo: 'II-019',
        nombre: 'Electivo de Formacion General III',
        sct: 3,
        nivel: 4,
      },
      {
        codigo: 'II-020',
        nombre: 'Comprension del Contexto Social',
        sct: 5,
        nivel: 5,
        requisitos: ['II-015'],
      },
      {
        codigo: 'II-021',
        nombre: 'Redes de Computadores',
        sct: 5,
        nivel: 5,
        requisitos: ['II-016'],
      },
      {
        codigo: 'II-022',
        nombre: 'Ingenieria de Software',
        sct: 7,
        nivel: 5,
        requisitos: ['II-017'],
      },
      {
        codigo: 'II-023',
        nombre: 'Especializacion Tecnologica I',
        sct: 7,
        nivel: 5,
        requisitos: ['II-017'],
      },
      { codigo: 'II-024', nombre: 'Ingles Tecnico I', sct: 3, nivel: 5 },
      {
        codigo: 'II-026',
        nombre: 'Diseno Interface Humano Computador',
        sct: 7,
        nivel: 6,
      },
      {
        codigo: 'II-027',
        nombre: 'Taller de Redes',
        sct: 5,
        nivel: 6,
        requisitos: ['II-021'],
      },
      {
        codigo: 'II-028',
        nombre: 'Ingenieria de Requerimientos',
        sct: 7,
        nivel: 6,
        requisitos: ['II-022'],
      },
      {
        codigo: 'II-029',
        nombre: 'Especializacion Tecnologica II',
        sct: 6,
        nivel: 6,
        requisitos: ['II-017'],
      },
      {
        codigo: 'II-030',
        nombre: 'Taller de Habilidades Profesionales I',
        sct: 4,
        nivel: 6,
      },
      {
        codigo: 'II-031',
        nombre: 'Direccion de Proyectos',
        sct: 6,
        nivel: 7,
        requisitos: ['II-020'],
      },
      {
        codigo: 'II-032',
        nombre: 'Ciberseguridad',
        sct: 5,
        nivel: 7,
        requisitos: ['II-021'],
      },
      {
        codigo: 'II-033',
        nombre: 'Arquitectura de Software',
        sct: 7,
        nivel: 7,
        requisitos: ['II-022'],
      },
      {
        codigo: 'II-034',
        nombre: 'Ingenieria de Datos',
        sct: 7,
        nivel: 7,
        requisitos: ['II-018'],
      },
      {
        codigo: 'II-035',
        nombre: 'Electivo de Formacion General IV',
        sct: 3,
        nivel: 7,
      },
      {
        codigo: 'II-036',
        nombre: 'Proyecto de Investigacion e Innovacion',
        sct: 5,
        nivel: 8,
      },
      {
        codigo: 'II-037',
        nombre: 'Tecnicas de Seguridad Aplicada',
        sct: 5,
        nivel: 8,
        requisitos: ['II-032'],
      },
      {
        codigo: 'II-038',
        nombre: 'Pruebas de Software',
        sct: 7,
        nivel: 8,
        requisitos: ['II-028', 'II-033'],
      },
      {
        codigo: 'II-039',
        nombre: 'Especializacion Tecnologica III',
        sct: 7,
        nivel: 8,
      },
      { codigo: 'II-040', nombre: 'Ingles Tecnico II', sct: 5, nivel: 8 },
      {
        codigo: 'II-042',
        nombre: 'Gestion de Proyectos de Software',
        sct: 7,
        nivel: 9,
        requisitos: ['II-031'],
      },
      {
        codigo: 'II-043',
        nombre: 'Proyecto de Integracion de Software',
        sct: 9,
        nivel: 9,
        requisitos: ['II-038'],
      },
      {
        codigo: 'II-044',
        nombre: 'Taller de Habilidades Profesionales II',
        sct: 4,
        nivel: 9,
        requisitos: ['II-030'],
      },
      {
        codigo: 'II-045',
        nombre: 'Actividad de Titulacion',
        sct: 30,
        nivel: 10,
        requisitos: REQUISITOS_II_HASTA_NIVEL_9,
      },
    ],
    modulosIngles: [
      { codigo: 'II-ING-1', nombre: 'Nivel Principiante', sct: 0, nivel: 1 },
      { codigo: 'II-ING-2', nombre: 'Nivel Basico', sct: 0, nivel: 2, requisitos: ['II-ING-1'] },
      { codigo: 'II-ING-3', nombre: 'Nivel Pre Intermedio', sct: 0, nivel: 3, requisitos: ['II-ING-2'] },
      { codigo: 'II-ING-4', nombre: 'Nivel Intermedio', sct: 0, nivel: 4, requisitos: ['II-ING-3'] },
    ],
    practicas: [
      {
        codigo: 'II-025',
        nombre: 'Practica I',
        sct: 9,
        nivel: 5,
        requisitos: REQUISITOS_II_HASTA_NIVEL_4,
      },
      {
        codigo: 'II-041',
        nombre: 'Practica II',
        sct: 9,
        nivel: 8,
        requisitos: REQUISITOS_II_HASTA_NIVEL_7,
      },
    ],
  },
];

export function estadoInicialAsignatura(
  asignatura: AsignaturaSeed,
): EstadoAsignatura {
  return asignatura.requisitos?.length
    ? EstadoAsignatura.Bloqueada
    : EstadoAsignatura.Disponible;
}
